 const cardsData = [
    {
    
      name: 'MINI COOPER S CLUBMAN. UNTOLD EDITION',
      image: 'https://images.ctfassets.net/xdc4scvw7fiv/2mOEfZWzd6qFu1NIkRh8Ed/c099f605d8a97680a891906db9126edd/cosySec.jpg',
      category: 'Mini Cooper',
      description: 'Spitzenleistung: 131 kW / (178 PS) | Hubraum: 1.998 cm3 | Kraftstoff: Benzin. Sonderausstattung: Bereifung mit Notlaufeigenschaften, MINI Connected, MINI Untold Edition, Sport-Lederlenkrad Nappa, Dach und Spiegelkappen in Wagenfarbe, Piano Black Exterieur, Fußmatten in Velours, Dachhimmel anthrazit, Premium Plus Paket (JCW Trim/Untold Edition).',
      city:"Bremen",
      actualStation:"Hauptbahnhof",
      available: true,
      linkUrl: '/buchung',
    },
  
    {
    
      name: 'MINI COOPER CABRIO. RESOLUTE EDITION',
      image: 'https://images.ctfassets.net/xdc4scvw7fiv/5tKroHsUzWTyplf3HQTKFp/dd1633890a033b6fe6917713b189b8e5/mini_cooper_cabrio_resolute_edition_18_pulse_spoke_schw.jpg',
      category: 'Mini Cooper',
      description: 'Leistung: 100 kW / 136 PS | Hubraum: 1.499 cm3 | Kraftstoff: Benzin. Sobderausstattung: Sonderausstattung: Notlaufeigenschaften, Sportsitze für Fahrer und Beifahrer, MINI Resolute Edition, Sport-Lederlenkrad Nappa, Außenspiegelkappen schwarz, Piano Black Exterieur, Resolute Exterieur, Fußmatten in Velours',
      linkUrl:  '/buchung',
      city:"Bremen",
      actualStation:"Hauptbahnhof",
      available: true,
    },
  
    {
      name: 'MINI COOPER 5-TÜRER',
      image: 'https://images.ctfassets.net/xdc4scvw7fiv/1PQdZ8VagcOmHMTBcSg10j/5a7a315ff48b5340f72be20caa87338e/cosySec.jpeg',
      category: 'Mini Cooper',
      description: 'Leistung: 100 kW / 136 PS | Hubraum: 1.499 cm3 | Kraftstoff: Benzin. Sonderausstattung: 16" LM Räder Victory Spoke schwarz, Midnight Black metallic, Stoff-/Leatherettekombination Black Pearl Carbon Black/Carbon Black, Interieuroberfläche Piano Black, Multifunktion für Lenkrad, Sport-Lederlenkrad, Reifendruck-Kontrolle, Warndreieck und Verbandkasten, Beifahrersitz-Höhenverstellung, Regensensor und automatische Fahrlichtsteuerung, Bordcomputer.',
      linkUrl:  '/buchung',
      city:"Bremen",
      actualStation:"Hauptbahnhof",
      available: true,
    },
  
    {
      name: 'MINI JOHN COOPER WORKS CABRIO',
      image: 'https://images.ctfassets.net/xdc4scvw7fiv/4lBfizS61BP2hq5abr7Ayk/dfdb06f89f99c46a6fb0b6ba4bf9bf93/cosySec__1_.jpeg',
      category: 'Mini Cooper',
      description: 'Leistung: 170 kW / 231 PS | Hubraum: 1.998 cm3| Kraftstoff: Benzin. Sonderausstattung: Melting Silver III, 17" LM Räder JCW Track Spoke schwarz, Interieuroberfläche Piano Black, Dinamica-/Stoffkombination Carbon Black, MINI Connected, Essential Trim, Spiegelkappen in Wagenfarbe, Premium Paket, Steuerung EfficientDynamics, Abgasnorm EU6 RDE II, EU spezifische Umfänge, Sport-Automatikgetriebe Steptronic, Real Time Traffic Information, Smartphone Integration, MINI Navigationssystem.',
      linkUrl:  '/buchung',
      city:"Bremen",
      actualStation:"Mahndorf",
      available: true,
    },
  
    {
      name: 'MINI JOHN COOPER WORKS COUNTRYMAN ALL4',
      image: 'https://images.ctfassets.net/xdc4scvw7fiv/5Wv0eeGUiCiD8tmx37QbHU/e8cf0f78660b1a6bc232d1df85baea11/cosySec__3_.jpeg',
      category: 'Mini Cooper',
      description: 'Leistung: 235 kW / 306 PS | Hubraum: 1.998 cm3| Kraftstoff: Benzin. Sonderausstattung: Melting Silver III, 18" John Cooper Works Black Grip Spoke, Interieuroberfläche Piano Black, Dinamica-/Stoffkombination Carbon Black, MINI Connected, Essential Trim, Dach und Spiegelkappen schwarz, DAB-Tuner, Intelligenter Notruf, Teleservices, Real Time Traffic Information, Smartphone Integration, MINI Connected XL, Telefonie mit Wireless Charging, MINI Navigationssystem, Aktiver Fussgängerschutzt.',
      linkUrl: '/buchung',
      city:"Bremen",
      actualStation:"Mahndorf",
      available: true,
    },
  
    {
      name: 'BMW 4ER GRAN COUPÉ',
      image: 'https://www.bmw-joas.de/wp-content/uploads/2022/07/4ergrancoupe.jpg.webp',
      category: 'BMW',
      description: 'Leistung: 135 kW (184 PS), Hubraum: 1.998 cm³, Kraftstoff: Benzin. Sonderausstattung: Das geschmackvolle Interieur besticht durch hochwertige Materialien, modernes Design und großzügigen Komfort. Zahlreiche Individualisierungsmöglichkeiten lassen ihr einzigartiges Wohlfühlambiente entstehen. Erfreuen Sie sich zudem an einer breiten Auswahl nützlicher und instinktiver Funktionen, die das Fahren noch angenehmer und sicherer machen. Auch beim Parken werden Sie durch den serienmäßigen Parking Assistant inklusive Rückfahrkamera unterstützt.',
      linkUrl:  '/buchung',
      city:"Bremen",
      actualStation:"Mahndorf",
      available: true,
    },
  
    {
      name: 'BMW X5',
      image: 'https://www.bmw-joas.de/wp-content/uploads/2022/10/the-bmx-x5-aussen.jpg.webp',
      category: 'BMW',
      description: 'Leistung: 210 kW (286 PS), Automatikgetriebe, Kraftstoff: Diesel. Sonderausstattung: Der BMW X5 strahlt Überlegenheit aus. Das optionale BMW Laserlicht mit blauen x-förmigen Elementen setzt ein deutliches ästhetisches Zeichen. So können Sie besser sehen und gesehen werden, ohne andere zu blenden.',
      linkUrl: '/buchung',
      city:"Bremen",
      actualStation:"flughafen",
      available: true,
    },
  
    {
      name: 'BMW i7 xDrive60 Limousine',
      image: 'https://derivates.kicker.de/image/upload/c_crop,x_0,y_90,w_2250,h_1266/w_1000,q_auto/v1/2022/11/05/4df15f8e-0073-4acf-809c-b39af95a616c.jpeg',
      category: 'BMW',
      description: 'Leistung: 400 kW (544 PS), Automatikgetriebe, Elektrische Auto. Sonderausstattung: Die Ladeperformance ist abhängig von Ladezustand, Umgebungstemperatur, individuellem Fahrprofil und Nutzung von Nebenverbrauchern. Die dargestellten Reichweiten sind bezogen auf den WLTP Best Case. Die Ladezeiten gelten für Umgebungstemperaturen von 23°C nach vorangegangener Fahrt und können entsprechend des Nutzungsverhaltens abweichen.',
      linkUrl: '/buchung',
      city:"Bremen",
      actualStation:"flughafen",
      available: true,
    },
  
    {
      name: 'BMW M850i xDrive Cabriolet',
      image: 'https://cdn.drivek.com/configurator-imgs/cars/de/800/BMW/M8-CABRIO/40945_CONVERTIBLE-2-DOORS/bmw-m8-convertible-2022-side-front.jpg',
      category: 'BMW',
      description: 'Leistung: 460 kW (625 PS), Automatikgetriebe, Kraftstoff: Benzin. Sonderausstattung: M Aerodynamikpaket, 19" M Leichtmetallräder & 18" M Sportbremse, M Einstiegsleisten, M Fahrerfußstütze und M spezifische Pedalerie, Exklusive Lackierungen und M spezifische Designelemente, Multifunktionssitze für Fahrer und Beifahrer in Leder Merino',
      linkUrl:  '/buchung',
      city:"Bremen",
      actualStation:"flughafen",
      available: true,
    },
  
    {
      name: 'BMW 3er TOURING',
      image: 'https://cdn.bimmertoday.de/wp-content/uploads/2022/05/BMW-3er-Touring-Facelift-2022-Basismodell-G21-LCI-1536x1024.jpg',
      category: 'BMW',
      description: 'Leistung: 375 kW (510 PS), Hubraum: 2.993 cm³, Kraftstoff: Benzin. Sonderausstattung: Innovative Bedienung durch moderne Technologien wie dem Intelligent Personal Assistant, Der Rückfahrassistent und weitere intelligente Fahrerassistenzsysteme für optimalen Fahrkomfort in jeder Situation, Fahrerorientiertes Cockpit und innovatives BMW Curved Display mit Touch-Bedienkonzept.',
      linkUrl: '/buchung',
      city:"Hamburg",
      actualStation:"flughafen",
      available: true,
    },
  
    {
      name: 'MERCEDES EQB 250',
      image: 'https://www.mercedes-benz.de/content/germany/de/passengercars/models/suv/x243-23-1/overview/_jcr_content/root/responsivegrid/highlight_copy/slider/image_95889.component.damq4.3366236953275.jpg/mercedes-eq-eqb-x243-exterior-paintfinish-06-3302x1858-03-2023.jpg',
      category: 'Mercedes-Benz',
      description: 'Leistung: 140 kW (190 PS), Automatikgetriebe, Elektrische Energie. Sonderausstattung: Der Aktive Spurhalte-Assistent kann Sie per Lenkradvibration warnen, falls Sie unbeabsichtigt eine Fahrbahnmarkierung überfahren. Der Geschwindigkeitslimit-Assistent macht es Ihnen leichter, die Vorgaben einzuhalten und unnötige Strafzettel zu vermeiden. Das System zeigt an, was erlaubt ist. Der Aktive Park-Assistent PARKTRONIC[1] unterstützt Sie beim Parken und Rangieren. Ultraschallsensoren überwachen den vorderen und rückwärtigen Bereich Ihres Fahrzeugs.',
      linkUrl:  '/buchung',
      city:"Bremen",
      actualStation:"flughafen",
      available: true,
    },
  
    {
      name: 'B-Klasse Sports Tourer',
      image: 'https://www.mercedes-benz.de/content/germany/de/passengercars/models/hatchback/b-class/overview/_jcr_content/root/responsivegrid/tabs_copy/tabitem/hotspot_module_1056677643/hotspot_simple_image.component.damq4.3366359117695.jpg/mercedes-benz-b-class-w247-exterior-hotspot-start-3302x1858-03-2023.jpg',
      category: 'Mercedes-Benz',
      description: 'Leistung: 110 kW (150 PS), Automatikgetriebe, Kraftstoff: Diesel. Sonderausstattung: DYNAMIC SELECT bietet auf Knopfdruck verschiedene Fahrprogramme, die beispielsweise Motor, Getriebe, Fahrwerk oder Lenkung vorbestimmen. Mit dem Fahrprogramm verändern Sie auch die Charakteristik des Doppelkupplungsgetriebes, wahlweise für effizientes Fahren mit niedrigen Drehzahlen oder für beeindruckende hohe Dynamik.',
      linkUrl:  '/buchung',
      city:"Bremen",
      actualStation:"flughafen",
      available: true,
    },
  
    {
      name: 'CLS Coupé',
      image: 'https://www.mercedes-benz.de/content/germany/de/passengercars/models/coupe/c257-22-2/overview/_jcr_content/root/responsivegrid/tabs_1275623578/tabitem/highlight/slider/image.component.damq4.3340151074436.jpg/mercedes-benz-cls-c257-manufaktur-exterior-09-3302x1858-11-2022.jpg',
      category: 'Mercedes-Benz',
      description: 'Leistung: 286 kW (350 PS), Automatikgetriebe, Kraftstoff: Diesel. Sonderausstattung: Der optional erhältliche GUARD 360° Fahrzeugschutz bietet eine Rundum-Überwachung des Fahrzeugumfelds – etwa mit der Einbruch- und Diebstahlwarnanlage und dem Abschleppschutz. Dieses hochentwickelte System möchten Sie vor allem im Kolonnenverkehr oder in Staus nicht mehr missen. Der Aktive Lenk-Assistent bietet Ihnen einen spürbaren Komfortgewinn am Steuer: Das System kann Sie mittels sanfter Lenkeingriffe dabei unterstützen, Ihr Fahrzeug mittig in der Fahrspur zu führen.',
      linkUrl:  '/buchung',
      city:"Hamburg",
      actualStation:"Hauptbahnhof",
      available: true,
    },
  
    {
      name: 'E-Klasse Cabriolet',
      category: 'Mercedes-Benz',
      image: 'https://www.mercedes-benz.de/content/germany/de/passengercars/models/cabriolet-roadster/a238-fl-22-2/overview/_jcr_content/root/responsivegrid/tabs/tabitem/hotspot_module/hotspot_simple_image.component.damq4.3340746004841.jpg/mercedes-benz-e-class-cabriolet-a238-exterior-hotspot-start-3302x1858-09-2022.jpg',
      description: 'Leistung: 110 kW (150 PS), Automatikgetriebe, Kraftstoff: Diesel. Sonderausstattung: .',
      linkUrl:  '/buchung',
      city:"Hamburg",
      actualStation:"Hauptbahnhof",
      available: true,
    },
  
    {
      name: 'Mercedes T-Klasse',
      category: 'Mercedes-Benz',
      image: 'https://www.mercedes-benz.de/content/germany/de/passengercars/models/van/t-class/overview/_jcr_content/root/responsivegrid/tabs/tabitem/hotspot_module/hotspot_simple_image.component.damq4.3328722527362.jpg/mercedes-benz-t-class-vs11-overview-exterior-highlights-sspip137150-3302x1858-05-2022.jpg',
      description: 'Leistung: 110 kW (150 PS), Automatikgetriebe, Kraftstoff: Diesel. Sonderausstattung: .',
      linkUrl:  '/buchung',
      city:"Hamburg",
      actualStation:"Hauptbahnhof",
      available: true,
    },
  
    {
      name: 'Toyota  Proace City Verso',
      category: 'Toyota',
      image: 'https://assets.meinauto.de/image/upload/f_auto/q_auto:eco/c_scale,w_2000/v1//prod/toyota/proacecityverso/1/5minimpv-combil2/toyota_20proacectyvermpvlwbmp1b_angularfront.png',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl: '/buchung',
      city:"Hamburg",
      actualStation:"Flughafen",
      available: true,
    },
  
    {
      name: 'Toyota  Yaris Hybrid',
      category: 'Toyota',
      image: 'https://www.meinauto.de/pics/auto_neuwagen/toyota-yaris-hybrid.png',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl:  '/buchung',
      city:"Hamburg",
      actualStation:"Flughafen",
      available: true,
    },
  
    {
      name: 'Toyota  Aygo X',
      category: 'Toyota',
      image: 'https://assets.meinauto.de/image/upload/f_auto/q_auto:eco/c_scale,w_2000/v1//prod/toyota/aygox/1/5suv-limited/toyota_22aygoxxlimitedsu1b_angularfront.png',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl:  '/buchung',
      linkUrl:  '/buchung',
      city:"Hamburg",
      actualStation:"Flughafen",
      available: true,
    },
  
    {
      name: 'Toyota  Corolla Hybrid',
      category: 'Toyota',
      image: 'https://assets.meinauto.de/image/upload/f_auto/q_auto:eco/c_scale,w_2000/v1//prod/toyota/corolla/12/5hatchback-hybridclub/toyota_19corollahybstylehb12b_angularfront.png',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl: '/buchung',
      linkUrl:  '/buchung',
      city:"Hamburg",
      actualStation:"Wilhemsburg",
      available: true,
    },
  
    {
      name: 'Toyota  C-HR Hybrid',
      category: 'Toyota',
      image: 'https://assets.meinauto.de/image/upload/f_auto/q_auto:eco/c_scale,w_2000/v1//prod/toyota/chr/1/5suv-team/toyota_20chrhybridclubsu1fb_angularfront.png',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl: '/buchung',
      city:"Hamburg",
      actualStation:"Wilhemsburg",
      available: true,
    },
  
    {
      name: 'Cupra Leon',
      category: 'Cupra',
      image: 'https://images.prismic.io/shacarlacca/ODBhZDg5YjItOTIyMy00MTVhLWJlMzAtMzk2OWUxYTdkMmM2__10.jpg?auto=compress%2Cformat&rect=0%2C0%2C1600%2C900&w=1200&h=1200',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl:  '/buchung',
      city:"Hamburg",
      actualStation:"Wilhemsburg",
      available: true,
    },
  
    {
      name: 'CUPRA Ateca 2.0',
      category: 'Cupra',
      image: 'https://www.schwaba.de/templates/yootheme/cache/10/cupra_ateca_beitrag-10a12ea7.webp',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl: '/buchung',
      city:"Berlin",
      actualStation:"Hauptbahnhof",
      available: true,
    },
  
    {
      name: 'CUPRA Formentor',
      category: 'Cupra',
      image: 'https://www.cupraofficial.com.tr/CupraFiles/202331523158367_CUPRA%20Formentor%201.5_XL.png',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl:  '/buchung',
      city:"Berlin",
      actualStation:"Hauptbahnhof",
      available: true,
    },
  
    {
      name: 'Cupra Born',
      category: 'Cupra',
      image: 'https://i0.wp.com/www.mobiflip.de/wp-content/uploads/2021/11/cupra-born-fahrt-header.jpg?w=1600&ssl=1',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl: '/buchung',
      city:"Berlin",
      actualStation:"Hauptbahnhof",
      available: true,
    },
  
    {
      name: 'Cupra Leon Kombi DSG',
      category: 'Cupra',
      image: 'https://aurento.de/wp-content/uploads/2023/03/Cupra-Leaon-ST-seitlich-weiss-800x800.jpg',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl: '/buchung',
      city:"Berlin",
      actualStation:"Flughafen",
      available: true,
    },
  
    {
      name: 'Tesla  Model X',
      category: 'Tesla',
      image: 'https://assets.meinauto.de/image/upload/f_auto/q_auto:eco/c_scale,w_2000/v1//prod/tesla/modelx/1/5suv-100d/tesla_17modelx100dod1b_angularfront.png',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl: '/buchung',
      city:"Berlin",
      actualStation:"Flughafen",
      available: true,
    },
  
    {
      name: 'Tesla Model 3',
      category: 'Tesla',
      image: 'https://assets.adac.de/image/upload/ar_16:9,c_fill,f_auto,g_auto,q_auto:eco,w_2000/v1/ADAC-eV/KOR/Bilder/PR/tesla-3-stehend-2301_vyxf0o',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl:  '/buchung',
      city:"Berlin",
      actualStation:"Flughafen",
      available: true,
    },
  
    {
      name: 'Tesla Model S',
      category: 'Tesla',
      image: 'https://assets.meinauto.de/image/upload/f_auto/q_auto:eco/c_scale,w_2000/v1//prod/tesla/models/1/5hatchback-plaid/tesla_21modelsplaid4wdhb1re_angularfront.png',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl: '/buchung',
      city:"Berlin",
      actualStation:"Kreuzberg",
      available: true,
    },
  
    {
      name: 'Tesla  Model Y',
      category: 'Tesla',
      image: 'https://assets.meinauto.de/image/upload/f_auto/q_auto:eco/c_scale,w_2000/v1//prod/tesla/modely/1/5suv-longrangeawd_4wd/tesla_22modelyevlongrng4wdsu1b_angularfront.png',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl:  '/buchung',
      city:"Berlin",
      actualStation:"Kreuzberg",
      available: true,
    },
  
    {
      name: 'Tesla Model Q',
      category: 'Tesla',
      image: 'https://insidetesla.de/wp-content/uploads/2021/09/tesla-model-q-21000-euro-auto.jpg',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl:  '/buchung',
      city:"Berlin",
      actualStation:"Kreuzberg",
      available: true,
    },
  
  
  
  
  
    {
      name: 'MINI COOPER S CLUBMAN. UNTOLD EDITION',
      image: 'https://images.ctfassets.net/xdc4scvw7fiv/2mOEfZWzd6qFu1NIkRh8Ed/c099f605d8a97680a891906db9126edd/cosySec.jpg',
      category: 'Mini Cooper',
      description: 'Spitzenleistung: 131 kW / (178 PS) | Hubraum: 1.998 cm3 | Kraftstoff: Benzin. Sonderausstattung: Bereifung mit Notlaufeigenschaften, MINI Connected, MINI Untold Edition, Sport-Lederlenkrad Nappa, Dach und Spiegelkappen in Wagenfarbe, Piano Black Exterieur, Fußmatten in Velours, Dachhimmel anthrazit, Premium Plus Paket (JCW Trim/Untold Edition).',
      city:"Berlin",
      actualStation:"Kreuzberg",
      available: true,
      linkUrl: '/buchung',
    },
  
    {
      name: 'MINI COOPER CABRIO. RESOLUTE EDITION',
      image: 'https://images.ctfassets.net/xdc4scvw7fiv/5tKroHsUzWTyplf3HQTKFp/dd1633890a033b6fe6917713b189b8e5/mini_cooper_cabrio_resolute_edition_18_pulse_spoke_schw.jpg',
      category: 'Mini Cooper',
      description: 'Leistung: 100 kW / 136 PS | Hubraum: 1.499 cm3 | Kraftstoff: Benzin. Sobderausstattung: Sonderausstattung: Notlaufeigenschaften, Sportsitze für Fahrer und Beifahrer, MINI Resolute Edition, Sport-Lederlenkrad Nappa, Außenspiegelkappen schwarz, Piano Black Exterieur, Resolute Exterieur, Fußmatten in Velours',
      linkUrl:  '/buchung',
      city:"Bremen",
      actualStation:"Hauptbahnhof",
      available: true,
    },
  
    {
      name: 'MINI COOPER 5-TÜRER',
      image: 'https://images.ctfassets.net/xdc4scvw7fiv/1PQdZ8VagcOmHMTBcSg10j/5a7a315ff48b5340f72be20caa87338e/cosySec.jpeg',
      category: 'Mini Cooper',
      description: 'Leistung: 100 kW / 136 PS | Hubraum: 1.499 cm3 | Kraftstoff: Benzin. Sonderausstattung: 16" LM Räder Victory Spoke schwarz, Midnight Black metallic, Stoff-/Leatherettekombination Black Pearl Carbon Black/Carbon Black, Interieuroberfläche Piano Black, Multifunktion für Lenkrad, Sport-Lederlenkrad, Reifendruck-Kontrolle, Warndreieck und Verbandkasten, Beifahrersitz-Höhenverstellung, Regensensor und automatische Fahrlichtsteuerung, Bordcomputer.',
      linkUrl:  '/buchung',
      city:"Niedersachsen",
      actualStation:"Hauptbahnhof",
      available: true,
    },
  
    {
      name: 'MINI JOHN COOPER WORKS CABRIO',
      image: 'https://images.ctfassets.net/xdc4scvw7fiv/4lBfizS61BP2hq5abr7Ayk/dfdb06f89f99c46a6fb0b6ba4bf9bf93/cosySec__1_.jpeg',
      category: 'Mini Cooper',
      description: 'Leistung: 170 kW / 231 PS | Hubraum: 1.998 cm3| Kraftstoff: Benzin. Sonderausstattung: Melting Silver III, 17" LM Räder JCW Track Spoke schwarz, Interieuroberfläche Piano Black, Dinamica-/Stoffkombination Carbon Black, MINI Connected, Essential Trim, Spiegelkappen in Wagenfarbe, Premium Paket, Steuerung EfficientDynamics, Abgasnorm EU6 RDE II, EU spezifische Umfänge, Sport-Automatikgetriebe Steptronic, Real Time Traffic Information, Smartphone Integration, MINI Navigationssystem.',
      linkUrl:  '/buchung',
      city:"Baden-Würtenberg",
      actualStation:"Heidenheim",
      available: true,
    },
  
    {
      name: 'MINI JOHN COOPER WORKS COUNTRYMAN ALL4',
      image: 'https://images.ctfassets.net/xdc4scvw7fiv/5Wv0eeGUiCiD8tmx37QbHU/e8cf0f78660b1a6bc232d1df85baea11/cosySec__3_.jpeg',
      category: 'Mini Cooper',
      description: 'Leistung: 235 kW / 306 PS | Hubraum: 1.998 cm3| Kraftstoff: Benzin. Sonderausstattung: Melting Silver III, 18" John Cooper Works Black Grip Spoke, Interieuroberfläche Piano Black, Dinamica-/Stoffkombination Carbon Black, MINI Connected, Essential Trim, Dach und Spiegelkappen schwarz, DAB-Tuner, Intelligenter Notruf, Teleservices, Real Time Traffic Information, Smartphone Integration, MINI Connected XL, Telefonie mit Wireless Charging, MINI Navigationssystem, Aktiver Fussgängerschutzt.',
      linkUrl: '/buchung',
      city:"Baden-Würtenberg",
      actualStation:"Heidenheim",
      available: true,
    },
  
    {
      name: 'BMW 4ER GRAN COUPÉ',
      image: 'https://www.bmw-joas.de/wp-content/uploads/2022/07/4ergrancoupe.jpg.webp',
      category: 'BMW',
      description: 'Leistung: 135 kW (184 PS), Hubraum: 1.998 cm³, Kraftstoff: Benzin. Sonderausstattung: Das geschmackvolle Interieur besticht durch hochwertige Materialien, modernes Design und großzügigen Komfort. Zahlreiche Individualisierungsmöglichkeiten lassen ihr einzigartiges Wohlfühlambiente entstehen. Erfreuen Sie sich zudem an einer breiten Auswahl nützlicher und instinktiver Funktionen, die das Fahren noch angenehmer und sicherer machen. Auch beim Parken werden Sie durch den serienmäßigen Parking Assistant inklusive Rückfahrkamera unterstützt.',
      linkUrl:  '/buchung',
      city:"Baden-Würtenberg",
      actualStation:"Heidenheim",
      available: true,
    },
  
    {
      name: 'BMW X5',
      image: 'https://www.bmw-joas.de/wp-content/uploads/2022/10/the-bmx-x5-aussen.jpg.webp',
      category: 'BMW',
      description: 'Leistung: 210 kW (286 PS), Automatikgetriebe, Kraftstoff: Diesel. Sonderausstattung: Der BMW X5 strahlt Überlegenheit aus. Das optionale BMW Laserlicht mit blauen x-förmigen Elementen setzt ein deutliches ästhetisches Zeichen. So können Sie besser sehen und gesehen werden, ohne andere zu blenden.',
      linkUrl: '/buchung',
      city:"Baden-Würtenberg",
      actualStation:"Geislingen",
      available: true,
    },
  
    {
      name: 'BMW i7 xDrive60 Limousine',
      image: 'https://derivates.kicker.de/image/upload/c_crop,x_0,y_90,w_2250,h_1266/w_1000,q_auto/v1/2022/11/05/4df15f8e-0073-4acf-809c-b39af95a616c.jpeg',
      category: 'BMW',
      description: 'Leistung: 400 kW (544 PS), Automatikgetriebe, Elektrische Auto. Sonderausstattung: Die Ladeperformance ist abhängig von Ladezustand, Umgebungstemperatur, individuellem Fahrprofil und Nutzung von Nebenverbrauchern. Die dargestellten Reichweiten sind bezogen auf den WLTP Best Case. Die Ladezeiten gelten für Umgebungstemperaturen von 23°C nach vorangegangener Fahrt und können entsprechend des Nutzungsverhaltens abweichen.',
      linkUrl: '/buchung',
      city:"Baden-Würtenberg",
      actualStation:"Geislingen",
      available: true,
    },
  
    {
      name: 'BMW M850i xDrive Cabriolet',
      image: 'https://cdn.drivek.com/configurator-imgs/cars/de/800/BMW/M8-CABRIO/40945_CONVERTIBLE-2-DOORS/bmw-m8-convertible-2022-side-front.jpg',
      category: 'BMW',
      description: 'Leistung: 460 kW (625 PS), Automatikgetriebe, Kraftstoff: Benzin. Sonderausstattung: M Aerodynamikpaket, 19" M Leichtmetallräder & 18" M Sportbremse, M Einstiegsleisten, M Fahrerfußstütze und M spezifische Pedalerie, Exklusive Lackierungen und M spezifische Designelemente, Multifunktionssitze für Fahrer und Beifahrer in Leder Merino',
      linkUrl:  '/buchung',
      city:"Baden-Würtenberg",
      actualStation:"Geislingen",
      available: true,
    },
  
    {
      name: 'BMW 3er TOURING',
      image: 'https://cdn.bimmertoday.de/wp-content/uploads/2022/05/BMW-3er-Touring-Facelift-2022-Basismodell-G21-LCI-1536x1024.jpg',
      category: 'BMW',
      description: 'Leistung: 375 kW (510 PS), Hubraum: 2.993 cm³, Kraftstoff: Benzin. Sonderausstattung: Innovative Bedienung durch moderne Technologien wie dem Intelligent Personal Assistant, Der Rückfahrassistent und weitere intelligente Fahrerassistenzsysteme für optimalen Fahrkomfort in jeder Situation, Fahrerorientiertes Cockpit und innovatives BMW Curved Display mit Touch-Bedienkonzept.',
      linkUrl: '/buchung',
      city:"Baden-Würtenberg",
      actualStation:"flughafen",
      available: true,
    },
  
    {
      name: 'MERCEDES EQB 250',
      image: 'https://www.mercedes-benz.de/content/germany/de/passengercars/models/suv/x243-23-1/overview/_jcr_content/root/responsivegrid/highlight_copy/slider/image_95889.component.damq4.3366236953275.jpg/mercedes-eq-eqb-x243-exterior-paintfinish-06-3302x1858-03-2023.jpg',
      category: 'Mercedes-Benz',
      description: 'Leistung: 140 kW (190 PS), Automatikgetriebe, Elektrische Energie. Sonderausstattung: Der Aktive Spurhalte-Assistent kann Sie per Lenkradvibration warnen, falls Sie unbeabsichtigt eine Fahrbahnmarkierung überfahren. Der Geschwindigkeitslimit-Assistent macht es Ihnen leichter, die Vorgaben einzuhalten und unnötige Strafzettel zu vermeiden. Das System zeigt an, was erlaubt ist. Der Aktive Park-Assistent PARKTRONIC[1] unterstützt Sie beim Parken und Rangieren. Ultraschallsensoren überwachen den vorderen und rückwärtigen Bereich Ihres Fahrzeugs.',
      linkUrl:  '/buchung',
      city:"Baden-Würtenberg",
      actualStation:"flughafen",
      available: true,
    },
  
    {
      name: 'B-Klasse Sports Tourer',
      image: 'https://www.mercedes-benz.de/content/germany/de/passengercars/models/hatchback/b-class/overview/_jcr_content/root/responsivegrid/tabs_copy/tabitem/hotspot_module_1056677643/hotspot_simple_image.component.damq4.3366359117695.jpg/mercedes-benz-b-class-w247-exterior-hotspot-start-3302x1858-03-2023.jpg',
      category: 'Mercedes-Benz',
      description: 'Leistung: 110 kW (150 PS), Automatikgetriebe, Kraftstoff: Diesel. Sonderausstattung: DYNAMIC SELECT bietet auf Knopfdruck verschiedene Fahrprogramme, die beispielsweise Motor, Getriebe, Fahrwerk oder Lenkung vorbestimmen. Mit dem Fahrprogramm verändern Sie auch die Charakteristik des Doppelkupplungsgetriebes, wahlweise für effizientes Fahren mit niedrigen Drehzahlen oder für beeindruckende hohe Dynamik.',
      linkUrl:  '/buchung',
      city:"Baden-Würtenberg",
      actualStation:"flughafen",
      available: true,
    },
  
    {
      name: 'CLS Coupé',
      image: 'https://www.mercedes-benz.de/content/germany/de/passengercars/models/coupe/c257-22-2/overview/_jcr_content/root/responsivegrid/tabs_1275623578/tabitem/highlight/slider/image.component.damq4.3340151074436.jpg/mercedes-benz-cls-c257-manufaktur-exterior-09-3302x1858-11-2022.jpg',
      category: 'Mercedes-Benz',
      description: 'Leistung: 286 kW (350 PS), Automatikgetriebe, Kraftstoff: Diesel. Sonderausstattung: Der optional erhältliche GUARD 360° Fahrzeugschutz bietet eine Rundum-Überwachung des Fahrzeugumfelds – etwa mit der Einbruch- und Diebstahlwarnanlage und dem Abschleppschutz. Dieses hochentwickelte System möchten Sie vor allem im Kolonnenverkehr oder in Staus nicht mehr missen. Der Aktive Lenk-Assistent bietet Ihnen einen spürbaren Komfortgewinn am Steuer: Das System kann Sie mittels sanfter Lenkeingriffe dabei unterstützen, Ihr Fahrzeug mittig in der Fahrspur zu führen.',
      linkUrl:  '/buchung',
      city:"Niedersachsen",
      actualStation:"Kaserne",
      available: true,
    },
  
    {
      name: 'E-Klasse Cabriolet',
      category: 'Mercedes-Benz',
      image: 'https://www.mercedes-benz.de/content/germany/de/passengercars/models/cabriolet-roadster/a238-fl-22-2/overview/_jcr_content/root/responsivegrid/tabs/tabitem/hotspot_module/hotspot_simple_image.component.damq4.3340746004841.jpg/mercedes-benz-e-class-cabriolet-a238-exterior-hotspot-start-3302x1858-09-2022.jpg',
      description: 'Leistung: 110 kW (150 PS), Automatikgetriebe, Kraftstoff: Diesel. Sonderausstattung: .',
      linkUrl:  '/buchung',
      city:"Niedersachsen",
      actualStation:"Kaserne",
      available: true,
    },
  
    {
      name: 'Mercedes T-Klasse',
      category: 'Mercedes-Benz',
      image: 'https://www.mercedes-benz.de/content/germany/de/passengercars/models/van/t-class/overview/_jcr_content/root/responsivegrid/tabs/tabitem/hotspot_module/hotspot_simple_image.component.damq4.3328722527362.jpg/mercedes-benz-t-class-vs11-overview-exterior-highlights-sspip137150-3302x1858-05-2022.jpg',
      description: 'Leistung: 110 kW (150 PS), Automatikgetriebe, Kraftstoff: Diesel. Sonderausstattung: .',
      linkUrl:  '/buchung',
      city:"Niedersachsen",
      actualStation:"Kaserne",
      available: true,
    },
  
    {
      name: 'Toyota  Proace City Verso',
      category: 'Toyota',
      image: 'https://assets.meinauto.de/image/upload/f_auto/q_auto:eco/c_scale,w_2000/v1//prod/toyota/proacecityverso/1/5minimpv-combil2/toyota_20proacectyvermpvlwbmp1b_angularfront.png',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl: '/buchung',
      city:"Niedersachsen",
      actualStation:"Flughafen",
      available: true,
    },
  
    {
      name: 'Toyota  Yaris Hybrid',
      category: 'Toyota',
      image: 'https://www.meinauto.de/pics/auto_neuwagen/toyota-yaris-hybrid.png',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl:  '/buchung',
      city:"Niedersachsen",
      actualStation:"Flughafen",
      available: true,
    },
  
    {
      name: 'Toyota  Aygo X',
      category: 'Toyota',
      image: 'https://assets.meinauto.de/image/upload/f_auto/q_auto:eco/c_scale,w_2000/v1//prod/toyota/aygox/1/5suv-limited/toyota_22aygoxxlimitedsu1b_angularfront.png',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl:  '/buchung',
      linkUrl:  '/buchung',
      city:"Niedersachsen",
      actualStation:"Flughafen",
      available: true,
    },
  
    {
      name: 'Toyota  Corolla Hybrid',
      category: 'Toyota',
      image: 'https://assets.meinauto.de/image/upload/f_auto/q_auto:eco/c_scale,w_2000/v1//prod/toyota/corolla/12/5hatchback-hybridclub/toyota_19corollahybstylehb12b_angularfront.png',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl: '/buchung',
      linkUrl:  '/buchung',
      city:"Niedersachsen",
      actualStation:"Hauptbahnhof",
      available: true,
    },
  
    {
      name: 'Toyota  C-HR Hybrid',
      category: 'Toyota',
      image: 'https://assets.meinauto.de/image/upload/f_auto/q_auto:eco/c_scale,w_2000/v1//prod/toyota/chr/1/5suv-team/toyota_20chrhybridclubsu1fb_angularfront.png',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl: '/buchung',
      city:"Niedersachsen",
      actualStation:"Hauptbahnhof",
      available: true,
    },
  
    {
      name: 'Cupra Leon',
      category: 'Cupra',
      image: 'https://images.prismic.io/shacarlacca/ODBhZDg5YjItOTIyMy00MTVhLWJlMzAtMzk2OWUxYTdkMmM2__10.jpg?auto=compress%2Cformat&rect=0%2C0%2C1600%2C900&w=1200&h=1200',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl:  '/buchung',
      city:"Niedersachsen",
      actualStation:"Hauptbahnhof",
      available: true,
    },
  
    {
      name: 'CUPRA Ateca 2.0',
      category: 'Cupra',
      image: 'https://www.schwaba.de/templates/yootheme/cache/10/cupra_ateca_beitrag-10a12ea7.webp',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl: '/buchung',
      city:"Saarland",
      actualStation:"Saarbrücken",
      available: true,
    },
  
    {
      name: 'CUPRA Formentor',
      category: 'Cupra',
      image: 'https://www.cupraofficial.com.tr/CupraFiles/202331523158367_CUPRA%20Formentor%201.5_XL.png',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl:  '/buchung',
      city:"Saarland",
      actualStation:"Saarbrücken",
      available: true,
    },
  
    {
      name: 'Cupra Born',
      category: 'Cupra',
      image: 'https://i0.wp.com/www.mobiflip.de/wp-content/uploads/2021/11/cupra-born-fahrt-header.jpg?w=1600&ssl=1',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl: '/buchung',
      city:"Saarland",
      actualStation:"Saarbrücken",
      available: true,
    },
  
    {
      name: 'Cupra Leon Kombi DSG',
      category: 'Cupra',
      image: 'https://aurento.de/wp-content/uploads/2023/03/Cupra-Leaon-ST-seitlich-weiss-800x800.jpg',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl: '/buchung',
      city:"Saarland",
      actualStation:"Hauptbahnhof",
      available: true,
    },
  
    {
      name: 'Tesla  Model X',
      category: 'Tesla',
      image: 'https://assets.meinauto.de/image/upload/f_auto/q_auto:eco/c_scale,w_2000/v1//prod/tesla/modelx/1/5suv-100d/tesla_17modelx100dod1b_angularfront.png',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl: '/buchung',
      city:"Saarland",
      actualStation:"Hauptbahnhof",
      available: true,
    },
  
    {
      name: 'Tesla Model 3',
      category: 'Tesla',
      image: 'https://assets.adac.de/image/upload/ar_16:9,c_fill,f_auto,g_auto,q_auto:eco,w_2000/v1/ADAC-eV/KOR/Bilder/PR/tesla-3-stehend-2301_vyxf0o',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl:  '/buchung',
      city:"Saarland",
      actualStation:"Hauptbahnhof",
      available: true,
    },
  
    {
      name: 'Tesla Model S',
      category: 'Tesla',
      image: 'https://assets.meinauto.de/image/upload/f_auto/q_auto:eco/c_scale,w_2000/v1//prod/tesla/models/1/5hatchback-plaid/tesla_21modelsplaid4wdhb1re_angularfront.png',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl: '/buchung',
      city:"Saarland",
      actualStation:"Schwalbach",
      available: true,
    },
  
    {
      name: 'Tesla  Model Y',
      category: 'Tesla',
      image: 'https://assets.meinauto.de/image/upload/f_auto/q_auto:eco/c_scale,w_2000/v1//prod/tesla/modely/1/5suv-longrangeawd_4wd/tesla_22modelyevlongrng4wdsu1b_angularfront.png',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl:  '/buchung',
      city:"Saarland",
      actualStation:"Schwalbach",
      available: true,
    },
  
    {
      name: 'Tesla Model Q',
      category: 'Tesla',
      image: 'https://insidetesla.de/wp-content/uploads/2021/09/tesla-model-q-21000-euro-auto.jpg',
      description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      linkUrl:  '/buchung',
      city:"Saarland",
      actualStation:"Schwalbach",
      available: true,
    },
  
  ];
  export default cardsData;